name: 04 - Using Actions

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v6
            - name: Printing Folders
              run: ls
            # - name: Use a third-party action
            #   uses: actions/setup-node@v3
            #   with:
            #     node-version: '14'
            # - name: Run a command
            #   run: node --version